services:
  hack_device_drivers:
    build: .
    privileged: true
    volumes:
      - .:/hack:cached
      # mount the host modules
      - /lib/modules:/lib/modules
      # mount the host kernel tree(s)
      - /usr/src:/kernel
    command: /bin/sh -c "while sleep 1000; do :; done"
    working_dir : /hack